add:
    path: /add
    defaults: { _controller: AppBundle:Location:add }
    methods: [POST]
list:
    path: /list
    defaults: { _controller: AppBundle:Location:list }
    methods: [GET]
summary:
    path: /summary
    defaults: { _controller: AppBundle:Location:summary }
    methods: [GET]
