AppBundle\Entity\Weather:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\WeatherRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lat:
            type: decimal
            precision: 4
            scale: 2
        lng:
            type: decimal
            precision: 5
            scale: 2
        name:
            type: string
            length: 255
        temp:
            type: float
        pressure:
            type: float
        humidity:
            type: smallint
        tempMin:
            type: float
            column: temp_min
        tempMax:
            type: float
            column: temp_max
        windSpeed:
            type: float
            column: wind_speed
        windDeg:
            type: float
            column: wind_deg
            nullable: true
        clouds:
            type: smallint
        rainOneH:
            type: float
            column: rain_one_h
            nullable: true
        rainThreeH:
            type: float
            column: rain_three_h
            nullable: true
        snowOneH:
            type: float
            column: snow_one_h
            nullable: true
        snowThreeH:
            type: float
            column: snow_three_h
            nullable: true
    lifecycleCallbacks: {  }
